// Client-safe fallback list of all gallery media files uploaded by Bilal
export const fallbackGalleryItems = [
  {
    id: 'g-0-AMNESTY',
    filename: 'AMNESTY Presinent certificate.jpeg',
    src: '/gallery/AMNESTY%20Presinent%20certificate.jpeg',
    title: 'Amnesty President Certificate',
    category: 'leadership',
    isVideo: false,
    date: '2025',
    location: 'FAST NUCES, Pakistan',
    description: 'President certificate awarded for leading Amnesty International FAST Chapter initiatives.'
  },
  {
    id: 'g-1-FastJobFair',
    filename: 'At FAST Islamabad Job FAIR.png',
    src: '/gallery/At%20FAST%20Islamabad%20Job%20FAIR.png',
    title: 'At FAST Islamabad Job Fair',
    category: 'university',
    isVideo: false,
    date: '2025',
    location: 'FAST Islamabad, Pakistan',
    description: 'Representing tech initiatives and engaging with industry leaders at FAST Islamabad Job Fair.'
  },
  {
    id: 'g-2-CertNeurosecure',
    filename: 'Certificate neurosecure.jpeg',
    src: '/gallery/Certificate%20neurosecure.jpeg',
    title: 'Certificate NeuroSecure',
    category: 'competitions',
    isVideo: false,
    date: '2025',
    location: 'FAST NUCES, Pakistan',
    description: 'Official award certificate for winning NeuroSecure AI project competition.'
  },
  {
    id: 'g-3-COLABS',
    filename: 'COLABS.jpeg',
    src: '/gallery/COLABS.jpeg',
    title: 'COLABS Tech Incubator',
    category: 'professional',
    isVideo: false,
    date: 'July 2026',
    location: 'Lahore, Pakistan',
    description: 'Engaging with tech founders, rocket interns, and HR leaders at COLABS.'
  },
  {
    id: 'g-4-COLABSTeam',
    filename: 'COLABS PK Team at ZORO Lahore.jpeg',
    src: '/gallery/COLABS%20PK%20Team%20at%20ZORO%20Lahore.jpeg',
    title: 'COLABS PK Team at ZORO Lahore',
    category: 'professional',
    isVideo: false,
    date: '2026',
    location: 'Lahore, Pakistan',
    description: 'Team collaboration and networking event with COLABS PK team.'
  },
  {
    id: 'g-5-Devsinc',
    filename: 'Devsinc.jpg',
    src: '/gallery/Devsinc.jpg',
    title: 'Devsinc Tech Company Visit',
    category: 'professional',
    isVideo: false,
    date: '2025',
    location: 'Lahore, Pakistan',
    description: 'Industry exposure and technical interaction at Devsinc headquarters.'
  },
  {
    id: 'g-6-DirectorFast',
    filename: 'Director (FAST CFD and Multan campus) at JOB Fair - representing entracloud.png',
    src: '/gallery/Director%20(FAST%20CFD%20and%20Multan%20campus)%20at%20JOB%20Fair%20-%20representing%20entracloud.png',
    title: 'Director FAST at Job Fair representing Entracloud',
    category: 'professional',
    isVideo: false,
    date: '2025',
    location: 'FAST NUCES',
    description: 'Meeting Director of FAST CFD & Multan campus while representing Entracloud at Job Fair.'
  },
  {
    id: 'g-7-DrAffan',
    filename: 'Dr, AFFAN and Dr. Mushtaq (both head of departments at JOB FAIR 2025) for my company entracloud.png',
    src: '/gallery/Dr,%20AFFAN%20and%20Dr.%20Mushtaq%20(both%20head%20of%20departments%20at%20JOB%20FAIR%202025)%20for%20my%20company%20entracloud.png',
    title: 'Dr. Affan & Dr. Mushtaq HODs at Job Fair 2025',
    category: 'professional',
    isVideo: false,
    date: '2025',
    location: 'FAST NUCES',
    description: 'Meeting CS HODs Dr. Affan and Dr. Mushtaq representing Entracloud company.'
  },
  {
    id: 'g-8-FASTLahore',
    filename: 'FAST Lahore visit.jpeg',
    src: '/gallery/FAST%20Lahore%20visit.jpeg',
    title: 'FAST Lahore Visit',
    category: 'university',
    isVideo: false,
    date: '2025',
    location: 'Lahore, Pakistan',
    description: 'Visiting FAST Lahore campus for tech symposium and inter-university meetups.'
  },
  {
    id: 'g-9-Palestine',
    filename: 'Head Palestine Desk.jpg',
    src: '/gallery/Head%20Palestine%20Desk.jpg',
    title: 'Head Palestine Desk Leadership',
    category: 'leadership',
    isVideo: false,
    date: '2024 - 2025',
    location: 'Islamabad, Pakistan',
    description: 'Leadership role managing awareness & student initiatives at Head Palestine Desk.'
  },
  {
    id: 'g-10-ICPCAward',
    filename: 'ICPC Award.jpeg',
    src: '/gallery/ICPC%20Award.jpeg',
    title: 'ICPC Award Recognition',
    category: 'competitions',
    isVideo: false,
    date: '2026',
    location: 'Pakistan Regional',
    description: 'Award recognition for competing in International Collegiate Programming Contest.'
  },
  {
    id: 'g-11-ICPCComp',
    filename: 'ICPC Competition - PUCIT Lahore.jpg',
    src: '/gallery/ICPC%20Competition%20-%20PUCIT%20Lahore.jpg',
    title: 'ICPC Competition at PUCIT Lahore',
    category: 'competitions',
    isVideo: false,
    date: '2026',
    location: 'PUCIT Lahore',
    description: 'Competitive programming with elite coders at ICPC PUCIT regional competition.'
  },
  {
    id: 'g-12-InternNIC',
    filename: 'Intern at NIC.jpeg',
    src: '/gallery/Intern%20at%20NIC.jpeg',
    title: 'Intern at National Incubation Center',
    category: 'internships',
    isVideo: false,
    date: '2025',
    location: 'Faisalabad, Pakistan',
    description: 'AI & Full Stack software development internship at National Incubation Center.'
  },
  {
    id: 'g-13-InternshipNIC',
    filename: 'Internship at NIC.jpeg',
    src: '/gallery/Internship%20at%20NIC.jpeg',
    title: 'AI Software Development Internship at NIC',
    category: 'internships',
    isVideo: false,
    date: '2025',
    location: 'Faisalabad, Pakistan',
    description: 'Building FastAPI backends and developer tools during NIC AI Internship.'
  },
  {
    id: 'g-14-Invozone',
    filename: 'Invozone compay.jpg',
    src: '/gallery/Invozone%20compay.jpg',
    title: 'Invozone Tech Company Visit',
    category: 'professional',
    isVideo: false,
    date: '2025',
    location: 'Lahore, Pakistan',
    description: 'Corporate software engineering engagement and networking at Invozone.'
  },
  {
    id: 'g-15-JobFair2025',
    filename: 'Job Fair 2025.jpg',
    src: '/gallery/Job%20Fair%202025.jpg',
    title: 'Job Fair 2025 Experience',
    category: 'university',
    isVideo: false,
    date: '2025',
    location: 'FAST NUCES',
    description: 'Recruitment & networking event at FAST NUCES Job Fair 2025.'
  },
  {
    id: 'g-16-MetroVideo',
    filename: 'METRO FSD Visit for computer networks peojct.mp4',
    src: '/gallery/METRO%20FSD%20Visit%20for%20computer%20networks%20peojct.mp4',
    title: 'METRO FSD Visit for Computer Networks Project',
    category: 'university',
    isVideo: true,
    date: '2025',
    location: 'Faisalabad, Pakistan',
    description: 'On-site industrial infrastructure analysis for Computer Networks course project.'
  },
  {
    id: 'g-17-NICAICenter',
    filename: 'NIC - AI Internship - Nationa Incubation center.jpg',
    src: '/gallery/NIC%20-%20AI%20Internship%20-%20Nationa%20Incubation%20center.jpg',
    title: 'NIC AI Internship Showcase',
    category: 'internships',
    isVideo: false,
    date: 'August 2025',
    location: 'National Incubation Center',
    description: 'Showcasing AI tools and automated Chrome extensions built during incubator program.'
  },
  {
    id: 'g-18-NeuroHire',
    filename: 'NeuroHire Team.jpeg',
    src: '/gallery/NeuroHire%20Team.jpeg',
    title: 'NeuroHire Team Collaboration',
    category: 'competitions',
    isVideo: false,
    date: '2025',
    location: 'FAST NUCES',
    description: 'Building NeuroHire AI automated screening platform with core founding team.'
  },
  {
    id: 'g-19-PresentationWinner',
    filename: 'Presentation Winner.jpeg',
    src: '/gallery/Presentation%20Winner.jpeg',
    title: 'Presentation Winner Award',
    category: 'competitions',
    isVideo: false,
    date: '2025',
    location: 'FAST NUCES',
    description: 'Secured 1st Place for AI technical pitch presentation.'
  },
  {
    id: 'g-20-ProgrammerForces',
    filename: 'Programmer Forces.jpg',
    src: '/gallery/Programmer%20Forces.jpg',
    title: 'Programmer Force Headquarters',
    category: 'professional',
    isVideo: false,
    date: '2025',
    location: 'Lahore, Pakistan',
    description: 'Exploring enterprise software architecture at Programmer Force.'
  },
  {
    id: 'g-21-PureLogics',
    filename: 'Pure Logics compan.jpg',
    src: '/gallery/Pure%20Logics%20compan.jpg',
    title: 'Pure Logics Company Visit',
    category: 'professional',
    isVideo: false,
    date: '2025',
    location: 'Lahore, Pakistan',
    description: 'Connecting with senior software architects at Pure Logics.'
  },
  {
    id: 'g-22-QAUMemory',
    filename: 'QAU Memory.jpeg',
    src: '/gallery/QAU%20Memory.jpeg',
    title: 'Quaid-i-Azam University Memory',
    category: 'memories',
    isVideo: false,
    date: '2024',
    location: 'Islamabad, Pakistan',
    description: 'Unforgettable campus visit to Quaid-i-Azam University.'
  },
  {
    id: 'g-23-ResearchLetter',
    filename: 'Research_Assistant_Offer_Letter_Bilal - ML Research.png',
    src: '/gallery/Research_Assistant_Offer_Letter_Bilal%20-%20ML%20Research.png',
    title: 'Machine Learning Research Assistant Offer Letter',
    category: 'university',
    isVideo: false,
    date: '2025',
    location: 'FAST NUCES',
    description: 'Official selection as Machine Learning Research Assistant under faculty guidance.'
  },
  {
    id: 'g-24-SeminarAmnesty',
    filename: 'Seminar - AMNESTY - Women Empowerment.jpeg',
    src: '/gallery/Seminar%20-%20AMNESTY%20-%20Women%20Empowerment.jpeg',
    title: 'Amnesty Seminar on Women Empowerment',
    category: 'leadership',
    isVideo: false,
    date: '2025',
    location: 'FAST Campus',
    description: 'Organizing and hosting campus-wide seminar on Women Empowerment & Human Rights.'
  },
  {
    id: 'g-25-VerifiedFreelancer',
    filename: 'Verified freelancer of pakistan.jpeg',
    src: '/gallery/Verified%20freelancer%20of%20pakistan.jpeg',
    title: 'Verified Freelancer Recognition',
    category: 'professional',
    isVideo: false,
    date: '2025',
    location: 'Pakistan',
    description: 'Official certification & recognition as Top Verified Freelancer in Pakistan.'
  },
  {
    id: 'g-26-WinningNeuroSecure',
    filename: 'Winning NeuroSecure Team.jpeg',
    src: '/gallery/Winning%20NeuroSecure%20Team.jpeg',
    title: 'Winning NeuroSecure AI Competition Team',
    category: 'competitions',
    isVideo: false,
    date: '2025',
    location: 'FAST NUCES',
    description: 'Celebrating 1st place victory with NeuroSecure AI system team.'
  },
  {
    id: 'g-27-Yieldwerx',
    filename: 'Yieldwerx semicondotor company - Last round interview.jpg',
    src: '/gallery/Yieldwerx%20semicondotor%20company%20-%20Last%20round%20interview.jpg',
    title: 'Yieldwerx Semiconductor Final Interview Round',
    category: 'professional',
    isVideo: false,
    date: '2025',
    location: 'Lahore, Pakistan',
    description: 'Final technical interview round at Yieldwerx Semiconductor software division.'
  }
];
